name: 'Dependency Check for SS19'
description: 'Github action to execute dependency check as part of a github workflow'
branding:
  icon: 'shield'
  color: 'red'
inputs:
  project:
    description: 'The name of the project to scan'
    required: true
  path:
    description: 'The path to scan'
    required: true
    default: '.'
  format:
    description: 'The output format to write to HTML, JSON (default), etc.'
    default: 'JSON'
    required: true
  out:
    description: 'The folder to write reports to. default is `reports`'
    required: true
    default: './reports'
  options:
    description: 'arguments options. See (Command Line Arguments)[https://jeremylong.github.io/DependencyCheck/dependency-check-cli/arguments.html]'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - '--project'
    - ${{ inputs.project }}
    - '--format'
    - ${{ inputs.format }}
    - ${{ inputs.options }}
    - '--noupdate'
    - '--out'
    - ${{ inputs.out }}
    - '--scan'
    - ${{ inputs.path }}